[build]
  command = "ng build --configuration production"
  publish = "dist/joker/browser"  # Adjust if your Angular project name differs

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
